package com.compraventa.persistencia.dominio;
// Generated 30/10/2012 12:50:17 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CompradoresVendedores generated by hbm2java
 */
@Entity
@Table(name="compradores_vendedores"
    ,catalog="coyote_db"
)
public class CompradoresVendedores  implements java.io.Serializable {


     private long idCvdr;
     private Localidades localidades;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String direccionAdicional;
     private String comentarios;
     private Set<TxCompraVentas> txCompraVentases = new HashSet<TxCompraVentas>(0);

    public CompradoresVendedores() {
    }

	
    public CompradoresVendedores(long idCvdr) {
        this.idCvdr = idCvdr;
    }
    public CompradoresVendedores(long idCvdr, Localidades localidades, String nombre, String apellidoPaterno, String apellidoMaterno, String direccionAdicional, String comentarios, Set<TxCompraVentas> txCompraVentases) {
       this.idCvdr = idCvdr;
       this.localidades = localidades;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.direccionAdicional = direccionAdicional;
       this.comentarios = comentarios;
       this.txCompraVentases = txCompraVentases;
    }
   
     @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_CVDR", unique=true, nullable=false)
    public long getIdCvdr() {
        return this.idCvdr;
    }
    
    public void setIdCvdr(long idCvdr) {
        this.idCvdr = idCvdr;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_LOCALIDAD")
    public Localidades getLocalidades() {
        return this.localidades;
    }
    
    public void setLocalidades(Localidades localidades) {
        this.localidades = localidades;
    }
    
    @Column(name="NOMBRE", length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="APELLIDO_PATERNO", length=20)
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    
    @Column(name="APELLIDO_MATERNO", length=20)
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    
    @Column(name="DIRECCION_ADICIONAL", length=50)
    public String getDireccionAdicional() {
        return this.direccionAdicional;
    }
    
    public void setDireccionAdicional(String direccionAdicional) {
        this.direccionAdicional = direccionAdicional;
    }
    
    @Column(name="COMENTARIOS", length=50)
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="compradoresVendedores")
    public Set<TxCompraVentas> getTxCompraVentases() {
        return this.txCompraVentases;
    }
    
    public void setTxCompraVentases(Set<TxCompraVentas> txCompraVentases) {
        this.txCompraVentases = txCompraVentases;
    }




}


