package com.compraventa.persistencia.dominio;
// Generated 30/10/2012 12:50:17 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompraVentas generated by hbm2java
 */
@Entity
@Table(name="compra_ventas"
    ,catalog="coyote_db"
)
public class CompraVentas  implements java.io.Serializable {


     private long idCvta;
     private Historicos historicos;
     private Submarcas submarcas;
     private Short modelo;
     private String color;
     private String placas;
     private String noSerie;
     private String tenenciasAdeudos;
     private Long idTx;
     private Double precioCompra;
     private Double precioVenta;
     private Double inversion;
     private Date fechaCompra;
     private Date fechaVenta;
     private Set<TxCompraVentas> txCompraVentases = new HashSet<TxCompraVentas>(0);

    public CompraVentas() {
    }

	
    public CompraVentas(long idCvta) {
        this.idCvta = idCvta;
    }
    public CompraVentas(long idCvta, Historicos historicos, Submarcas submarcas, Short modelo, String color, String placas, String noSerie, String tenenciasAdeudos, Long idTx, Double precioCompra, Double precioVenta, Double inversion, Date fechaCompra, Date fechaVenta, Set<TxCompraVentas> txCompraVentases) {
       this.idCvta = idCvta;
       this.historicos = historicos;
       this.submarcas = submarcas;
       this.modelo = modelo;
       this.color = color;
       this.placas = placas;
       this.noSerie = noSerie;
       this.tenenciasAdeudos = tenenciasAdeudos;
       this.idTx = idTx;
       this.precioCompra = precioCompra;
       this.precioVenta = precioVenta;
       this.inversion = inversion;
       this.fechaCompra = fechaCompra;
       this.fechaVenta = fechaVenta;
       this.txCompraVentases = txCompraVentases;
    }
   
     @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_CVTA", unique=true, nullable=false)
    public long getIdCvta() {
        return this.idCvta;
    }
    
    public void setIdCvta(long idCvta) {
        this.idCvta = idCvta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_HISTORICO")
    public Historicos getHistoricos() {
        return this.historicos;
    }
    
    public void setHistoricos(Historicos historicos) {
        this.historicos = historicos;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_SUBMARCA")
    public Submarcas getSubmarcas() {
        return this.submarcas;
    }
    
    public void setSubmarcas(Submarcas submarcas) {
        this.submarcas = submarcas;
    }
    
    @Column(name="MODELO")
    public Short getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Short modelo) {
        this.modelo = modelo;
    }
    
    @Column(name="COLOR", length=50)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    
    @Column(name="PLACAS", length=15)
    public String getPlacas() {
        return this.placas;
    }
    
    public void setPlacas(String placas) {
        this.placas = placas;
    }
    
    @Column(name="NO_SERIE", length=50)
    public String getNoSerie() {
        return this.noSerie;
    }
    
    public void setNoSerie(String noSerie) {
        this.noSerie = noSerie;
    }
    
    @Column(name="TENENCIAS_ADEUDOS", length=50)
    public String getTenenciasAdeudos() {
        return this.tenenciasAdeudos;
    }
    
    public void setTenenciasAdeudos(String tenenciasAdeudos) {
        this.tenenciasAdeudos = tenenciasAdeudos;
    }
    
    @Column(name="ID_TX")
    public Long getIdTx() {
        return this.idTx;
    }
    
    public void setIdTx(Long idTx) {
        this.idTx = idTx;
    }
    
    @Column(name="PRECIO_COMPRA", precision=22, scale=0)
    public Double getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(Double precioCompra) {
        this.precioCompra = precioCompra;
    }
    
    @Column(name="PRECIO_VENTA", precision=22, scale=0)
    public Double getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(Double precioVenta) {
        this.precioVenta = precioVenta;
    }
    
    @Column(name="INVERSION", precision=22, scale=0)
    public Double getInversion() {
        return this.inversion;
    }
    
    public void setInversion(Double inversion) {
        this.inversion = inversion;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_COMPRA", length=10)
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_VENTA", length=10)
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="compraVentas")
    public Set<TxCompraVentas> getTxCompraVentases() {
        return this.txCompraVentases;
    }
    
    public void setTxCompraVentases(Set<TxCompraVentas> txCompraVentases) {
        this.txCompraVentases = txCompraVentases;
    }




}


