package com.compraventa.persistencia.dominio;
// Generated 30/10/2012 12:50:17 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Conceptos generated by hbm2java
 */
@Entity
@Table(name="conceptos"
    ,catalog="coyote_db"
)
public class Conceptos  implements java.io.Serializable {


     private short idConcepto;
     private String nombre;
     private String comentarios;
     private Set<TxCompraVentas> txCompraVentases = new HashSet<TxCompraVentas>(0);

    public Conceptos() {
    }

	
    public Conceptos(short idConcepto) {
        this.idConcepto = idConcepto;
    }
    public Conceptos(short idConcepto, String nombre, String comentarios, Set<TxCompraVentas> txCompraVentases) {
       this.idConcepto = idConcepto;
       this.nombre = nombre;
       this.comentarios = comentarios;
       this.txCompraVentases = txCompraVentases;
    }
   
     @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_CONCEPTO", unique=true, nullable=false)
    public short getIdConcepto() {
        return this.idConcepto;
    }
    
    public void setIdConcepto(short idConcepto) {
        this.idConcepto = idConcepto;
    }
    
    @Column(name="NOMBRE", length=15)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="COMENTARIOS", length=20)
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="conceptos")
    public Set<TxCompraVentas> getTxCompraVentases() {
        return this.txCompraVentases;
    }
    
    public void setTxCompraVentases(Set<TxCompraVentas> txCompraVentases) {
        this.txCompraVentases = txCompraVentases;
    }




}


