package com.compraventa.persistencia.dominio;
// Generated 30/10/2012 12:50:17 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Estados generated by hbm2java
 */
@Entity
@Table(name="estados"
    ,catalog="coyote_db"
)
public class Estados  implements java.io.Serializable {


     private short id;
     private String clave;
     private String nombre;
     private String abrev;

    public Estados() {
    }

	
    public Estados(short id) {
        this.id = id;
    }
    public Estados(short id, String clave, String nombre, String abrev) {
       this.id = id;
       this.clave = clave;
       this.nombre = nombre;
       this.abrev = abrev;
    }
   
     @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID", unique=true, nullable=false)
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    
    @Column(name="CLAVE", length=2)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    
    @Column(name="NOMBRE", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="ABREV", length=16)
    public String getAbrev() {
        return this.abrev;
    }
    
    public void setAbrev(String abrev) {
        this.abrev = abrev;
    }




}


