package com.compraventa.persistencia.dominio;
// Generated 30/10/2012 12:50:17 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Localidades generated by hbm2java
 */
@Entity
@Table(name="localidades"
    ,catalog="coyote_db"
)
public class Localidades  implements java.io.Serializable {


     private int id;
     private Municipios municipios;
     private String clave;
     private String nombre;
     private String latitud;
     private String longitud;
     private String altitud;
     private Set<CompradoresVendedores> compradoresVendedoreses = new HashSet<CompradoresVendedores>(0);

    public Localidades() {
    }

	
    public Localidades(int id) {
        this.id = id;
    }
    public Localidades(int id, Municipios municipios, String clave, String nombre, String latitud, String longitud, String altitud, Set<CompradoresVendedores> compradoresVendedoreses) {
       this.id = id;
       this.municipios = municipios;
       this.clave = clave;
       this.nombre = nombre;
       this.latitud = latitud;
       this.longitud = longitud;
       this.altitud = altitud;
       this.compradoresVendedoreses = compradoresVendedoreses;
    }
   
     @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MUNICIPIO_ID")
    public Municipios getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Municipios municipios) {
        this.municipios = municipios;
    }
    
    @Column(name="CLAVE", length=4)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    
    @Column(name="NOMBRE", length=110)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="LATITUD", length=6)
    public String getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }
    
    @Column(name="LONGITUD", length=7)
    public String getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }
    
    @Column(name="ALTITUD", length=4)
    public String getAltitud() {
        return this.altitud;
    }
    
    public void setAltitud(String altitud) {
        this.altitud = altitud;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="localidades")
    public Set<CompradoresVendedores> getCompradoresVendedoreses() {
        return this.compradoresVendedoreses;
    }
    
    public void setCompradoresVendedoreses(Set<CompradoresVendedores> compradoresVendedoreses) {
        this.compradoresVendedoreses = compradoresVendedoreses;
    }




}


