package com.compraventa.persistencia.dominio;
// Generated 30/10/2012 12:50:17 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Municipios generated by hbm2java
 */
@Entity
@Table(name="municipios"
    ,catalog="coyote_db"
)
public class Municipios  implements java.io.Serializable {


     private int id;
     private Short estadoId;
     private String clave;
     private String nombre;
     private String sigla;
     private Set<Localidades> localidadeses = new HashSet<Localidades>(0);

    public Municipios() {
    }

	
    public Municipios(int id) {
        this.id = id;
    }
    public Municipios(int id, Short estadoId, String clave, String nombre, String sigla, Set<Localidades> localidadeses) {
       this.id = id;
       this.estadoId = estadoId;
       this.clave = clave;
       this.nombre = nombre;
       this.sigla = sigla;
       this.localidadeses = localidadeses;
    }
   
     @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="ESTADO_ID")
    public Short getEstadoId() {
        return this.estadoId;
    }
    
    public void setEstadoId(Short estadoId) {
        this.estadoId = estadoId;
    }
    
    @Column(name="CLAVE", length=3)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    
    @Column(name="NOMBRE", length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="SIGLA", length=4)
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="municipios")
    public Set<Localidades> getLocalidadeses() {
        return this.localidadeses;
    }
    
    public void setLocalidadeses(Set<Localidades> localidadeses) {
        this.localidadeses = localidadeses;
    }




}


