package com.compraventa.persistencia.dominio;
// Generated 30/10/2012 05:18:45 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolesUsuario generated by hbm2java
 */
@Entity
@Table(name="roles_usuario"
    ,catalog="coyote_db"
)
public class RolesUsuario  implements java.io.Serializable {


     private Integer idUsrRol;
     private Usuarios usuarios;
     private Roles roles;

    public RolesUsuario() {
    }

    public RolesUsuario(Usuarios usuarios, Roles roles) {
       this.usuarios = usuarios;
       this.roles = roles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_USR_ROL", unique=true, nullable=false)
    public Integer getIdUsrRol() {
        return this.idUsrRol;
    }
    
    public void setIdUsrRol(Integer idUsrRol) {
        this.idUsrRol = idUsrRol;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USR")
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ROL")
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }




}


