package com.compraventa.persistencia.dominio;
// Generated 30/10/2012 12:50:17 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Submarcas generated by hbm2java
 */
@Entity
@Table(name="submarcas"
    ,catalog="coyote_db"
)
public class Submarcas  implements java.io.Serializable {


     private int idSubmarca;
     private Marcas marcas;
     private String nombre;
     private String descripcion;
     private Set<Historicos> historicoses = new HashSet<Historicos>(0);
     private Set<CompraVentas> compraVentases = new HashSet<CompraVentas>(0);

    public Submarcas() {
    }

	
    public Submarcas(int idSubmarca, String nombre) {
        this.idSubmarca = idSubmarca;
        this.nombre = nombre;
    }
    public Submarcas(int idSubmarca, Marcas marcas, String nombre, String descripcion, Set<Historicos> historicoses, Set<CompraVentas> compraVentases) {
       this.idSubmarca = idSubmarca;
       this.marcas = marcas;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.historicoses = historicoses;
       this.compraVentases = compraVentases;
    }
   
     @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_SUBMARCA", unique=true, nullable=false)
    public int getIdSubmarca() {
        return this.idSubmarca;
    }
    
    public void setIdSubmarca(int idSubmarca) {
        this.idSubmarca = idSubmarca;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_MARCA")
    public Marcas getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Marcas marcas) {
        this.marcas = marcas;
    }
    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="DESCRIPCION", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="submarcas")
    public Set<Historicos> getHistoricoses() {
        return this.historicoses;
    }
    
    public void setHistoricoses(Set<Historicos> historicoses) {
        this.historicoses = historicoses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="submarcas")
    public Set<CompraVentas> getCompraVentases() {
        return this.compraVentases;
    }
    
    public void setCompraVentases(Set<CompraVentas> compraVentases) {
        this.compraVentases = compraVentases;
    }




}


