package com.compraventa.persistencia.dominio;
// Generated 30/10/2012 12:50:17 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TxCompraVentas generated by hbm2java
 */
@Entity
@Table(name="tx_compra_ventas"
    ,catalog="coyote_db"
)
public class TxCompraVentas  implements java.io.Serializable {


     private long idTxCvta;
     private CompradoresVendedores compradoresVendedores;
     private CompraVentas compraVentas;
     private Conceptos conceptos;
     private String ifeRuta;
     private String responsivaRuta;
     private String otrosRuta;

    public TxCompraVentas() {
    }

	
    public TxCompraVentas(long idTxCvta) {
        this.idTxCvta = idTxCvta;
    }
    public TxCompraVentas(long idTxCvta, CompradoresVendedores compradoresVendedores, CompraVentas compraVentas, Conceptos conceptos, String ifeRuta, String responsivaRuta, String otrosRuta) {
       this.idTxCvta = idTxCvta;
       this.compradoresVendedores = compradoresVendedores;
       this.compraVentas = compraVentas;
       this.conceptos = conceptos;
       this.ifeRuta = ifeRuta;
       this.responsivaRuta = responsivaRuta;
       this.otrosRuta = otrosRuta;
    }
   
     @Id 
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ID_TX_CVTA", unique=true, nullable=false)
    public long getIdTxCvta() {
        return this.idTxCvta;
    }
    
    public void setIdTxCvta(long idTxCvta) {
        this.idTxCvta = idTxCvta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_COMPRADOR_VENDEDOR")
    public CompradoresVendedores getCompradoresVendedores() {
        return this.compradoresVendedores;
    }
    
    public void setCompradoresVendedores(CompradoresVendedores compradoresVendedores) {
        this.compradoresVendedores = compradoresVendedores;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CVTA")
    public CompraVentas getCompraVentas() {
        return this.compraVentas;
    }
    
    public void setCompraVentas(CompraVentas compraVentas) {
        this.compraVentas = compraVentas;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CONCEPTO")
    public Conceptos getConceptos() {
        return this.conceptos;
    }
    
    public void setConceptos(Conceptos conceptos) {
        this.conceptos = conceptos;
    }
    
    @Column(name="IFE_RUTA", length=50)
    public String getIfeRuta() {
        return this.ifeRuta;
    }
    
    public void setIfeRuta(String ifeRuta) {
        this.ifeRuta = ifeRuta;
    }
    
    @Column(name="RESPONSIVA_RUTA", length=50)
    public String getResponsivaRuta() {
        return this.responsivaRuta;
    }
    
    public void setResponsivaRuta(String responsivaRuta) {
        this.responsivaRuta = responsivaRuta;
    }
    
    @Column(name="OTROS_RUTA", length=50)
    public String getOtrosRuta() {
        return this.otrosRuta;
    }
    
    public void setOtrosRuta(String otrosRuta) {
        this.otrosRuta = otrosRuta;
    }




}


