package com.compraventa.persistencia.dominio;
// Generated 30/10/2012 05:18:45 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="coyote_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="NOMBRE_USUARIO") 
)
public class Usuarios  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombreUsuario;
     private String nombreReal;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private Short activo;
     private String password;
     private Set<RolesUsuario> rolesUsuarios = new HashSet<RolesUsuario>(0);

    public Usuarios() {
    }

    public Usuarios(String nombreUsuario, String nombreReal, String apellidoPaterno, String apellidoMaterno, Short activo, String password, Set<RolesUsuario> rolesUsuarios) {
       this.nombreUsuario = nombreUsuario;
       this.nombreReal = nombreReal;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.activo = activo;
       this.password = password;
       this.rolesUsuarios = rolesUsuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_USUARIO", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    
    @Column(name="NOMBRE_USUARIO", unique=true, length=15)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    
    @Column(name="NOMBRE_REAL", length=25)
    public String getNombreReal() {
        return this.nombreReal;
    }
    
    public void setNombreReal(String nombreReal) {
        this.nombreReal = nombreReal;
    }
    
    @Column(name="APELLIDO_PATERNO", length=20)
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    
    @Column(name="APELLIDO_MATERNO", length=20)
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    
    @Column(name="ACTIVO")
    public Short getActivo() {
        return this.activo;
    }
    
    public void setActivo(Short activo) {
        this.activo = activo;
    }
    
    @Column(name="PASSWORD", length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set<RolesUsuario> getRolesUsuarios() {
        return this.rolesUsuarios;
    }
    
    public void setRolesUsuarios(Set<RolesUsuario> rolesUsuarios) {
        this.rolesUsuarios = rolesUsuarios;
    }




}


